version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db_820
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: webdb
    ports:
      - "8806:3306"
    volumes:
      - mysql_db_820:/var/lib/mysql
    networks:
      - webdb820
    restart: always

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_820
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: "root"
      UPLOAD_LIMIT: 64M
    ports:
      - "8830:80"
    depends_on:
      - db
    networks:
      - webdb820
    restart: always

networks:
  webdb820:
    driver: bridge

volumes:
  mysql_db_820:
    driver: local
